config/routes.rb
Rails.application.routes.draw do
  resources :to_dos do
    resources :notes
  end
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "weather", to: "weather#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :to_do
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    # I'm following the guide linked below, but I think I could omit the patenthesis here because ruby, gonna keep them because that feels more natural as a non ruby dev, but can change my standard
    # https://guides.rubyonrails.org/v7.2/getting_started.html
    @to_do = ToDo.find(params[:to_do_id])
    @note = @to_do.notes.create(note_params)
    redirect_to to_do_path(@to_do)
  end

  def destroy
    @to_do = ToDo.find(params[:to_do_id])
    @note = @to_do.notes.find(params[:id])
    @note.destroy
    # @to_do.notes.destroy(@note)
    redirect_to to_do_path(@to_do)
  end

  private
    def note_params
      params.require(:note).permit(:body)
    end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: %i[ show edit update destroy ]

  # GET /to_dos or /to_dos.json
  def index
    @to_dos = ToDo.all
  end

  # GET /to_dos/1 or /to_dos/1.json
  def show
  end

  # GET /to_dos/new
  def new
    @to_do = ToDo.new
  end

  # GET /to_dos/1/edit
  def edit
  end

  # POST /to_dos or /to_dos.json
  def create
    @to_do = ToDo.new(to_do_params)

    respond_to do |format|
      if @to_do.save
        format.html { redirect_to @to_do, notice: "To do was successfully created." }
        format.json { render :show, status: :created, location: @to_do }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_dos/1 or /to_dos/1.json
  def update
    respond_to do |format|
      if @to_do.update(to_do_params)
        format.html { redirect_to @to_do, notice: "To do was successfully updated." }
        format.json { render :show, status: :ok, location: @to_do }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1 or /to_dos/1.json
  def destroy
    # commenty comment
    @to_do.destroy!

    respond_to do |format|
      format.html { redirect_to to_dos_path, status: :see_other, notice: "To do was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do
      @to_do = ToDo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def to_do_params
      params.expect(to_do: [ :title, :completed ])
    end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
    city = params[:city] || "New York"
    api_key = ENV["OPEN_WEATHER_KEY"]
    # instead of this, get lat and lon from geo api using city value
    # https://openweathermap.org/api/geocoding-api
    lat = params[:lat] || "40.7128"
    lon = params[:lon] || "-74.0060"
    url = "http://api.openweathermap.org/data/3.0/weather?lat=#{lat}&lon=#{lon}&appid=#{api_key}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<h2>Hello World!!!</h2>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Helloworld" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_dos/_form.html.erb
<%= form_with(model: to_do) do |form| %>
  <% if to_do.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
        <% to_do.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.checkbox :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/to_dos/_note.html.erb
<div>
  <p><strong>Note:</strong> <%= note.body %></p>
  <p><strong>Created at:</strong> <%= note.created_at %></p>
  <%= button_to "Delete this note", to_do_note_path(@to_do, note), method: :delete %>
</div>

app/views/to_dos/_note_form.html.erb
<%= form_with model: [ to_do, to_do.notes.build ] do |form| %>
  <%= form.label :body %>
  <%= form.text_area :body %>

  <%= form.submit "Create Note" %>
<% end %>

app/views/to_dos/_to_do.html.erb
<div id="<%= dom_id to_do %>">
  <p>
    <strong>Title:</strong>
    <%= to_do.title %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= to_do.completed %>
  </p>

</div>

app/views/to_dos/edit.html.erb
<% content_for :title, "Editing to do" %>

<h1>Editing to do</h1>

<%= render "form", to_do: @to_do %>

<br>

<div>
  <%= link_to "Show this to do", @to_do %> |
  <%= link_to "Back to to dos", to_dos_path %>
</div>

app/views/to_dos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "To dos" %>

<h1>To dos</h1>

<div id="to_dos">
  <% @to_dos.each do |to_do| %>
    <%= render to_do %>
    <p>
      <%= link_to "Show this to do", to_do %>
    </p>
  <% end %>
</div>

<%= link_to "New to do", new_to_do_path %>

app/views/to_dos/new.html.erb
<% content_for :title, "New to do" %>

<h1>New to do</h1>

<%= render "form", to_do: @to_do %>

<br>

<div>
  <%= link_to "Back to to dos", to_dos_path %>
</div>

app/views/to_dos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @to_do %>

<div>
  <%= link_to "Edit this to do", edit_to_do_path(@to_do) %> |
  <%= link_to "Back to to dos", to_dos_path %>

  <%= button_to "Destroy this to do", @to_do, method: :delete %>

  <h2>Notes</h2>
  <%= render partial: "to_dos/note", collection: @to_do.notes, as: :note %>

  <%= render partial: "to_dos/note_form", locals: { to_do: @to_do } %>
</div>

app/views/weather/index.html.erb
<h1>Weather Page</h1>